name: "Feature Request"
description: RFC and ideas for new features and improvements
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: "Description"
      description: "Please provide a description of the feature or enhancement."
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Example"
      description: |
        A simple example of the new feature in action (include PHP code, YAML config, etc.)
        If the new feature changes an existing feature, include a simple before/after comparison.
  - type: input
    attributes:
      label: ArshWell Version
      description: "The ArshWell version if for a specific major/minor."
      placeholder: "x.y"
    validations:
      required: false
